name: "Lint R related files"
description: "Check the coding style of all .R, .Rmd and .Rnw files in a folder"
inputs:
  repository:
    description: 'Repository name with owner. For example, actions/checkout'
    default: ${{ github.repository }}
  token:
    description: >
      Personal access token (PAT) used to fetch the repository. The PAT is configured
      with the local git config, which enables your scripts to run authenticated git
      commands. The post-job step removes the PAT.


      We recommend using a service account with the least permissions necessary.
      Also when generating a new PAT, select the least scopes necessary.


      [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
    default: ${{ github.token }}
  path:
    description: >
      Which path must be checked. This path is relative to the root of the repository.
    default: "."
  regexp:
    description: >
      Regexp pattern to select which files to test. The default pattern handles .R; .Rmd and .Rnw files
    default: "\\\\.(R|r)(md|nw)+"
runs:
  using: 'docker'
  image: docker://inbobmk/github_actions
  entrypoint: '/lint_src.sh'
  args:
    - ${{ inputs.repository }}
    - ${{ inputs.token }}
    - ${{ inputs.path }}
    - ${{ inputs.regexp }}
