name: "NARA2020"
description: "Render the background documents for NARA 2020. https://www.vlaanderen.be/inbo/inbo-natuurrapporten/"
inputs:
  repository:
    description: 'Repository name with owner. For example, actions/checkout'
    default: ${{ github.repository }}
  token:
    description: >
      Personal access token (PAT) used to fetch the repository. The PAT is configured
      with the local git config, which enables your scripts to run authenticated git
      commands. The post-job step removes the PAT.


      We recommend using a service account with the least permissions necessary.
      Also when generating a new PAT, select the least scopes necessary.


      [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
    default: ${{ github.token }}
  publish:
    description: >
      Publish the background documents. 0 for test render only. 1 for render and publish. Note that 0 implies checking out $GITHUB_SHA$. Whereas 1 implies checking out main.
    default: 0
runs:
  using: 'docker'
  image: docker://inbobmk/nara2020
  args:
    - ${{ inputs.repository }}
    - ${{ inputs.token }}
    - ${{ inputs.publish }}
